### ISSUE TITLE
Python 3.11: mismatch in test_it_shows_errors

### ISSUE THREAD

**Issue by ptrcnull** [delfick/nose-of-yeti#18]
now that the exceptions underline parts of code that are wrong, the expected output doesn't match:
```
GOT LINES
=========
msg = """
Traceback (most recent call last):
File ".../nose-of-yeti-release-2.4.1/noseOfYeti/tokeniser/spec_codec.py", line 136, in dealwith
    self.tokeniser.translate(readline, data, **kwargs)
File "/usr/lib/python3.11/unittest/mock.py", line 1118, in __call__
    return self._mock_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/unittest/mock.py", line 1122, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/unittest/mock.py", line 1177, in _execute_mock_call
    raise effect
Exception: NOPE
"""
raise Exception(f"--- internal spec codec error --- \n{msg}")



WANT LINES
==========
msg = """
Traceback \(most recent call last\):
File ".+noseOfYeti/tokeniser/spec_codec.py", line \d+, in dealwith
    self.tokeniser.translate\(readline, data, \*\*kwargs\)
File ".+unittest/mock.py", line \d+.+
    .+
File ".+unittest/mock.py", line \d+.+
    .+
File ".+unittest/mock.py", line \d+.+
    .+
Exception: NOPE
"""
raise Exception\(f"--- internal spec codec error --- \\n\{msg\}"\)
```

**Comment by delfick** [comment]
well that's annoying. I'm sick with the spicy cough atm but once I'm
recovered I'll make it more like a similar test I've done recently
somewhere where it doesn't care so much about missing lines

**Comment by delfick** [comment]
I spent a few minutes to make it so that test works in 3.11 and CI now tests against 3.11

:)

**Comment by ptrcnull** [comment]
thanks!
