### ISSUE TITLE
Test failure: noseOfYeti.specs.spec_codec_test.Test_RegisteringCodec.test_registering_codec_doesnt_lead_to_error

### ISSUE THREAD

**Issue by gi11es** [delfick/nose-of-yeti#8]
`gilles@thumbor:~/nose-of-yeti/nose-of-yeti-master$ ./test.sh
..................................................F......................................
======================================================================
FAIL: noseOfYeti.specs.spec_codec_test.Test_RegisteringCodec.test_registering_codec_doesnt_lead_to_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/gilles/nose-of-yeti/nose-of-yeti-master/noseOfYeti/specs/spec_codec_test.py", line 59, in test_registering_codec_doesnt_lead_to_error
    process.returncode |should| be(0)
  File "/usr/lib/python2.7/dist-packages/should_dsl/dsl.py", line 30, in __or__
    return self._check_expectation()
  File "/usr/lib/python2.7/dist-packages/should_dsl/dsl.py", line 36, in _check_expectation
    self._rvalue.message_for_failed_should())
ShouldNotSatisfied: 1 was expected to be 0
-------------------- >> begin captured stdout << ---------------------
Traceback (most recent call last):
  File "/tmp/tmp0mk6Bs/script.py", line 1, in <module>
    import spec_setup; import codez
  File "/tmp/tmp0mk6Bs/spec_setup.py", line 2, in <module>
    from noseOfYeti.tokeniser.spec_codec import register_from_options
ImportError: No module named noseOfYeti.tokeniser.spec_codec

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 89 tests in 0.611s

FAILED (failures=1)`

**Comment by delfick** [comment]
hmmmmm, interesting.

So if you install noseOfYeti and run ./test.sh again does it work?

I just ran the following commands and it worked fine for me

    mkvirtualenv nose-of-yeti
    pip install -e .
    pip install -e ".[tests]"
    ./test.sh

**Comment by gi11es** [comment]
Fixed it by specifying PYTHONPATH
It was specific to the environment I was running the tests in (build phase of a debian package).
